import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import Header from "~/app/_components/header";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Tracker",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`font-sans ${inter.variable} mx-auto flex h-screen max-w-[1280px] flex-col bg-[#131313] text-gray-400`}
      >
        <TRPCReactProvider>
          <Header />
          <main className="flex-grow">{children}</main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
